//PROVINSI

export const FIND_PROVS_REQUEST = "FIND_PROVS_REQUEST";
export const FIND_PROVS_SUCCESS = "FIND_PROVS_SUCCESS";
export const FIND_PROVS_FAILURE = "FIND_PROVS_FAILURE";

export const SAVE_PROV_REQUEST = "SAVE_PROV_REQUEST";
export const SAVE_PROV_SUCCESS = "SAVE_PROV_SUCCESS";
export const SAVE_PROV_FAILURE = "SAVE_PROV_FAILURE";

export const DELETE_PROV_REQUEST = "DELETE_PROV_REQUEST";
export const DELETE_PROV_SUCCESS = "DELETE_PROV_SUCCESS";
export const DELETE_PROV_FAILURE = "DELETE_PROV_FAILURE";

export const FIND_PROV_REQUEST = "FIND_PROV_REQUEST";
export const FIND_PROV_SUCCESS = "FIND_PROV_SUCCESS";
export const FIND_PROV_FAILURE = "FIND_PROV_FAILURE";
