//PROVINSI
export const FIND_PROVS_REQUEST = "FIND_PROVS_REQUEST";
export const FIND_PROVS_SUCCESS = "FIND_PROVS_SUCCESS";
export const FIND_PROVS_FAILURE = "FIND_PROVS_FAILURE";

export const SAVE_PROV_REQUEST = "SAVE_PROV_REQUEST";
export const SAVE_PROV_SUCCESS = "SAVE_PROV_SUCCESS";
export const SAVE_PROV_FAILURE = "SAVE_PROV_FAILURE";

export const DELETE_PROV_REQUEST = "DELETE_PROV_REQUEST";
export const DELETE_PROV_SUCCESS = "DELETE_PROV_SUCCESS";
export const DELETE_PROV_FAILURE = "DELETE_PROV_FAILURE";

export const FIND_PROV_REQUEST = "FIND_PROV_REQUEST";
export const FIND_PROV_SUCCESS = "FIND_PROV_SUCCESS";
export const FIND_PROV_FAILURE = "FIND_PROV_FAILURE";

//PEMAKAI
export const FIND_PKONTRASEPSIS_REQUEST = "FIND_PKONTRASEPSIS_REQUEST";
export const FIND_PKONTRASEPSIS_SUCCESS = "FIND_PKONTRASEPSIS_SUCCESS";
export const FIND_PKONTRASEPSIS_FAILURE = "FIND_PKONTRASEPSIS_FAILURE";

export const SAVE_PKONTRASEPSI_REQUEST = "SAVE_PKONTRASEPSI_REQUEST";
export const SAVE_PKONTRASEPSI_SUCCESS = "SAVE_PKONTRASEPSI_SUCCESS";
export const SAVE_PKONTRASEPSI_FAILURE = "SAVE_PKONTRASEPSI_FAILURE";

export const DELETE_PKONTRASEPSI_REQUEST = "DELETE_PKONTRASEPSI_REQUEST";
export const DELETE_PKONTRASEPSI_SUCCESS = "DELETE_PKONTRASEPSI_SUCCESS";
export const DELETE_PKONTRASEPSI_FAILURE = "DELETE_PKONTRASEPSI_FAILURE";

export const FIND_PKONTRASEPSI_REQUEST = "FIND_PKONTRASEPSI_REQUEST";
export const FIND_PKONTRASEPSI_SUCCESS = "FIND_PKONTRASEPSI_SUCCESS";
export const FIND_PKONTRASEPSI_FAILURE = "FIND_PKONTRASEPSI_FAILURE";