insert into list_provinsi(id,nama_provinsi) values (1,'Aceh');
insert into list_provinsi(id,nama_provinsi) values (2,'Sumatera Utara');
insert into list_provinsi(id,nama_provinsi) values (3,'Sumatera Barat');
insert into list_provinsi(id,nama_provinsi) values (4,'Riau');
insert into list_provinsi(id,nama_provinsi) values (5,'Kepulauan Riau');
insert into list_provinsi(id,nama_provinsi) values (6,'Jambi');
insert into list_provinsi(id,nama_provinsi) values (7,'Bangka Belitung');
insert into list_provinsi(id,nama_provinsi) values (8,'Sumatera Selatan');
insert into list_provinsi(id,nama_provinsi) values (9,'Lampung');
insert into list_konstrasepsi(id,nama_konstrasepsi) values (1,'Pil');
insert into list_konstrasepsi(id,nama_konstrasepsi) values (2,'Kondom');
insert into list_konstrasepsi(id,nama_konstrasepsi) values (3,'IUD');
insert into list_list_pemakai_kontrasepsi(id,jumlah_pemakai,kontrasepsi_id,provinsi_id) values (1, 10, 1, 1);
